name: Petclinic CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: push docker images
      run: ./scripts/hellobash.sh
    - name: push docker images
      run : ./scripts/pushImages.sh

