name: Test Variables
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print some default env variables
      run: |
        echo "HOME: ${HOME}"
        echo "REPOSITORY_PREFIX: ${REPOSITORY_PREFIX}"
        echo "USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}"
        echo "PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}"
        echo "REPOSITORY_PREFIX2: $REPOSITORY_PREF"
      shell: bash
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
