name: Petclinic CD
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
        aws-region: eu-west-3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update kube config
      #run: aws eks update-kubeconfig --name petclinic_cluster
      run: |
        pwd & ls
        cat ./k8s/*.yaml | sed 's#\${REPOSITORY_PREFIX}'"#${REPOSITORY_PREFIX}#g" | > deploy.yaml
        cat deploy.yaml 

    - name: Initialization of namespace EKS
      uses: kodermax/kubectl-aws-eks@main
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          get ns spring-petclinic || kubectl create ns spring-petclinic # create namespace if not exists
          

    - name: Initialization of services Amazon EKS
      uses: kodermax/kubectl-aws-eks@main
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          kubectl delete secret db-secret-customers-service -n spring-petclinic --ignore-not-found
          kubectl create secret generic db-secret-customers-service --from-literal=password=petclinic -n spring-petclinic
          kubectl delete secret db-secret-visits-service -n spring-petclinic --ignore-not-found
          kubectl create secret generic db-secret-visits-service --from-literal=password=petclinic -n spring-petclinic
          kubectl delete secret db-secret-visits-service -n spring-petclinic --ignore-not-found
          kubectl create secret generic db-secret-visits-service --from-literal=password=petclinic -n spring-petclinic

    - name: Initialization of deployment Amazon EKS
      uses: kodermax/kubectl-aws-eks@main
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          kubectl apply -f k8s/

    - name: add conf kub
      uses: kodermax/kubectl-aws-eks@main
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          config view --raw >~/.kube/config
          
    - name: Initialization of services Amazon EKS
      uses: kodermax/kubectl-aws-eks@main
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          kubectl apply -f k8s/init-services

    - name: get api 
      uses: kodermax/kubectl-aws-eks@main
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          get svc -n spring-petclinic api-gateway 
