name: Test Variables
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print some default env variables
      run: |
        echo "USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}"
        echo "PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}"
      shell: bash
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
