name: Petclinic CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      env:
        REPOSITORY_PREFIX: ${{ vars.REPOSITORY_PREFIX }}
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Packaging with Maven
      run: mvn -B package --file pom.xml
    - name: Build Services & générer les images docker
      run: mvn spring-boot:build-image --file pom.xml -X  -Pk8s -DREPOSITORY_PREFIX=${REPOSITORY_PREFIX}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push docker images
      run : ./scripts/pushImages.sh
